name: My pytest workflow
on: [push]
jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --junitxml=junit/test-results.xml
        pytest --cov=mymodule > pytest-coverage.txt

    - name: Test Report
      uses: pmeier/pytest-results-action@main
      if: always()    # run this step even if previous step failed
      with:
        path: junit/*-results.xml    # Path to test results

    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt